poll/urls.py
from django.urls import path

from . import views #from here import...

app_name = 'poll'
urlpatterns = [
    #ex: /polls/
    path("", views.IndexView.as_view, name="index"),
    #ex: /polls/5/
    #lo que esta en question id es lo que se pasara por parametro a la funcion
    #ex: /polls/5/details
    path("<int:pk>/", views.DetailView.as_view, name="detail"),
    #ex: /polls/5/results
    path("<int:pk>/results/", views.ResultView.as_view, name="results"),
    #ex: /polls/5/vote
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

# "< >/ is the way we pass parameters and variables through the url we are setting"

premiosplatziapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("poll/", include("poll.urls"))
]

poll/models.py
from datetime import timezone
import datetime
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text




        

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from poll.models import Choice, Question
from django.views import generic

#function based view
#every function works with requests and http response 
#def index(request):
#    latest_question_list = Question.objects.all()
#    return render(request, "poll/index.html", {
#        "latest_question_list": latest_question_list
#    })

#def detail(request, question_id):
#    """details of every question"""
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'poll/detail.html', {'question': question})


#def results(request, question_id):
#    """details of every question result"""
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'poll/results.html', {'question': question})


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'


class ResultView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request, question_id):
    """Functions for voting confirmation"""
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        pass
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "Tu no elegiste ninguna opción",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

poll/templates/poll/detail.html
<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>
                {{ question.question_text }}
            </h1>
        </legend>
        {% if error_message %}
        <p><strong>
            {{ error_message }}
        </strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio"
                name="choice"
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"
            >
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }} 
            </label>
        {% endfor %}
    </fieldset>
<button type="submit" >votar</button>
</form>

poll/templates/poll/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}        
            <li> <a href="{% url 'poll:detail' question.id %}">{{ question.question_text}}</a></li> 
        {% endfor%}   
    <ul>
{% else %}<p> No polls are available. </p>

{% endif %}

poll/templates/poll/results.html
<h1>{{question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes | pluralize}}
            
        </li>
    {% endfor %}    
</ul>
<a href="{% url 'poll:detail' question.id %}">Te gustaria votar de nuevo?</a>